version: '3.9'

services:
  nginx:
    container_name: devcle-nginx-test
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx-test
    volumes: []
    networks:
      - devcle-network

  core:
    container_name: devcle-core-test
    build:
      context: ./core
      target: development
      dockerfile: ../docker/Dockerfile.core
    env_file: .env.test
    environment:
      NODE_ENV: test
      CI: "true"
      # Override to use docker network names instead of IPs
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_URL: postgresql://devcle:test_password_only@postgres:5432/devcle_test
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://:test_redis_password_only@redis:6379/0
    command: sh -c "pnpm dev"
    networks:
      - devcle-network
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: devcle-postgres-test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
      - ./infra/postgres/init.sh:/docker-entrypoint-initdb.d/01-init.sh:ro
      - ./infra/postgres/rls.sql:/docker-entrypoint-initdb.d/02-rls.sql:ro
    networks:
      - devcle-network
    restart: unless-stopped
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: devcle-redis-test
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: sh -c 'redis-server /usr/local/etc/redis/redis.conf --requirepass "${REDIS_PASSWORD}"'
    volumes:
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data-test:/data
    networks:
      - devcle-network
    restart: unless-stopped
    ports:
      - "56379:6379"
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a ${REDIS_PASSWORD} PING"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data-test:
  redis-data-test:

networks:
  devcle-network:
    driver: bridge
