version: '3.9'

services:
  nginx:
    container_name: devcle-nginx-test
    volumes:
      - ./certs/devcle.test+3.pem:/etc/nginx/certs/server.crt:ro
      - ./certs/devcle.test+3-key.pem:/etc/nginx/certs/server.key:ro

  core:
    container_name: devcle-core-test
    build:
      target: development
      dockerfile: ../docker/Dockerfile.core
    environment:
      DATABASE_URL: postgresql://devcle:test_password_only@postgres:5432/devcle_test
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      POSTGRES_USER: devcle
      POSTGRES_DB: devcle_test
      POSTGRES_PASSWORD: test_password_only
      REDIS_URL: redis://:test_redis_password_only@redis:6379/0
      REDIS_PASSWORD: test_redis_password_only
      SESSION_SECRET: test_session_secret_safe_to_commit
      ENCRYPTION_KEY: IoEizZo+c7ZB+BAk83VvJhfRS9g0uPiuTRIGQ5Kc4h0=
      APP_DOMAIN: devcle.test
      BASE_URL: https://devcle.test
      NODE_ENV: test
      CI: "true"
    volumes:
      - ./core:/app
      - core-node-modules-test:/app/node_modules
    command: sh -c "pnpm install --frozen-lockfile && pnpm dev"
    networks:
      - devcle-network
    ports:
      - "3001:3000"

  postgres:
    image: postgres:15-alpine
    container_name: devcle-postgres-test
    environment:
      POSTGRES_DB: devcle_test
      POSTGRES_USER: devcle
      POSTGRES_PASSWORD: test_password_only
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
      - ./infra/postgres/init.sh:/docker-entrypoint-initdb.d/01-init.sh:ro
      - ./infra/postgres/rls.sql:/docker-entrypoint-initdb.d/02-rls.sql:ro
    networks:
      - devcle-network
    restart: unless-stopped
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devcle"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: devcle-redis-test
    environment:
      REDIS_PASSWORD: test_redis_password_only
    command: sh -c 'redis-server /usr/local/etc/redis/redis.conf --requirepass "test_redis_password_only"'
    volumes:
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data-test:/data
    networks:
      - devcle-network
    restart: unless-stopped
    ports:
      - "56379:6379"
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a test_redis_password_only PING"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  core-node-modules-test:
  postgres-data-test:
  redis-data-test:

networks:
  devcle-network:
    driver: bridge
